# serverless.yml

service: predict

package:
  individually: true

provider:
  name: aws
  runtime: python3.6

functions:
  predict:
    handler: predict.predict
    module: predict

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
